/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinalpateq13;

import java.io.*;
import java.nio.file.*;
import java.util.List;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fomi0
 */
public class Frame extends javax.swing.JFrame {
    
    Boolean busquedaActiva = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frame.class.getName());

    /**
     * Creates new form Frame
     */
    public Frame() {
        //Se obtiene la instancia del gestor de libros
        GestorLibros gestor = GestorLibros.getInstancia();
        
        //Se lee el archivo de los libros y se agregan a la lista de libros del gestor.
        gestor.cargarLibrosDeArchivo();
        
        //Se inician los componentes gráficos
        initComponents();
        
        //Se llena la tabla con Todos los libros.
        llenarTablaConLibros();
    }
    
    private void llenarTablaConLibros(){
        //Se obitene la instancia del gestor y se obtienen todos los libros en la lista.
        GestorLibros gestor = GestorLibros.getInstancia();
        List<Libro> libros = gestor.getLibros();
        
        DefaultTableModel modelo = (DefaultTableModel) tablaLibros.getModel();
        
        modelo.setRowCount(0);
        
        for(Libro libro: libros){
            Object[] fila = new Object[]{
                libro.getISBN(),
                libro.getTipo(),
                libro.getTitulo(),
                libro.getAutor(),
                libro.getAnio(),
                libro.getGenero()
            };
            modelo.addRow(fila);
        }
    }

    private void llenarTablaConResultados(List<Libro> libros){
        //Se obitene la instancia del gestor y se obtienen todos los libros en la lista.
        DefaultTableModel modelo = (DefaultTableModel) tablaLibros.getModel();
        
        modelo.setRowCount(0);
        
        for(Libro libro: libros){
            Object[] fila = new Object[]{
                libro.getISBN(),
                libro.getTipo(),
                libro.getTitulo(),
                libro.getAutor(),
                libro.getAnio(),
                libro.getGenero()
            };
            modelo.addRow(fila);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        criterioSelect = new javax.swing.JComboBox<>();
        valorBusquedaInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tituloInput = new javax.swing.JTextField();
        generoInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        autorInput = new javax.swing.JTextField();
        anioInput = new javax.swing.JTextField();
        tipoSelect = new javax.swing.JComboBox<>();
        registrarLibroBtn = new javax.swing.JButton();
        mensajeErrorLbl = new javax.swing.JLabel();
        isbnInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLbl.setText("Todos los libros");

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Tipo", "Titulo", "Autor", "Año", "Género"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaLibros);

        jLabel7.setText("Búsqueda");

        criterioSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autor", "ISBN", "Titulo" }));

        jLabel8.setText("Criterio de búsqueda");

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("José Fong, Andrés Le Gresley, Leonardo Canett (2025)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloLbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorBusquedaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(criterioSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarBtn))
                    .addComponent(jLabel9))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(criterioSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorBusquedaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(buscarBtn))
                .addGap(31, 31, 31)
                .addComponent(tituloLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        jTabbedPane1.addTab("Buscar libro", jPanel1);

        jLabel1.setText("Tipo");

        jLabel2.setText("Autor");

        jLabel3.setText("Título");

        jLabel4.setText("Género");

        jLabel5.setText("Año");

        anioInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioInputKeyTyped(evt);
            }
        });

        tipoSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novela", "Enciclopedia" }));
        tipoSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoSelectActionPerformed(evt);
            }
        });

        registrarLibroBtn.setText("Registrar Libro");
        registrarLibroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarLibroBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("ISBN");

        jLabel10.setText("José Fong, Andrés Le Gresley, Leonardo Canett (2025)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(anioInput)
                                    .addComponent(generoInput)))
                            .addComponent(registrarLibroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(autorInput)
                            .addComponent(tituloInput)
                            .addComponent(tipoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isbnInput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(mensajeErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isbnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tipoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tituloInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(autorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(anioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(generoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(registrarLibroBtn))
                    .addComponent(mensajeErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar Libro", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoSelectActionPerformed

    //Validación para permitir solo números en el campo de año
    private void anioInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioInputKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_anioInputKeyTyped

    private void registrarLibroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarLibroBtnActionPerformed
        //Extracción de información de cada input o select
        String isbn = isbnInput.getText().trim();
        String tipo = tipoSelect.getSelectedItem().toString();
        String titulo = tituloInput.getText().trim();
        String autor = autorInput.getText().trim();
        String anio = anioInput.getText().trim();
        String genero = generoInput.getText().trim();
        
        //Validación para que se completen todos los campos
        if(isbn.equals("") || titulo.equals("") || genero.equals("") || autor.equals("") || anio.equals("")){
            mensajeErrorLbl.setText("Complete todos los campos.");
        }else{
            //Validación para que ningun dato contenga ";"
            if(isbn.contains(";") || titulo.contains(";") || autor.contains(";") || tipo.contains(";") || genero.contains(";") || anio.contains(";")){
                mensajeErrorLbl.setText("No puede usar ; en ninguno de los campos.");
            }else{
                //Se obtiene la instancia UNICA del gestor de libros y se agrega el libro
                GestorLibros gestor = GestorLibros.getInstancia();
                
                //Se agrega el libro a la lista de libros y al archivo
                gestor.agregarLibro(isbn, tipo, titulo, autor, anio, genero);
                gestor.agregarLibroAlArchivo(isbn, tipo, titulo, autor, anio, genero);
                
                //Se reinician los inputs
                isbnInput.setText("");
                tituloInput.setText("");
                generoInput.setText("");
                autorInput.setText("");
                anioInput.setText("");
                
                //Se muestra un mensaje de éxito.
                mensajeErrorLbl.setText("Libro '"+titulo+"' de '"+autor+"' registrado correctamente.");
            
                //Se actualiza la tabla
                llenarTablaConLibros();
            }   
        }
    }//GEN-LAST:event_registrarLibroBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        if(busquedaActiva){
            //Se elimina el valor de la busqueda
            valorBusquedaInput.setText("");
            
            //Se llena la tabla con todos los libros
            llenarTablaConLibros();
            
            //Se regresa el botón de buscar y se desactiva busqueda activa
            busquedaActiva = false;
            buscarBtn.setText("Buscar");
            
        }else{
            //Se extraen criterio y valor de busqueda
            String criterio = criterioSelect.getSelectedItem().toString().trim().toLowerCase();
            String valor = valorBusquedaInput.getText().trim().toLowerCase();

            if(criterio.equals("") || valor.equals("")){
                System.out.println("Error al realizar la busqueda.");
            }else{
                //Crear los buscadores
                BuscadorLibro buscadorAutor = new BusquedaPorAutor();
                BuscadorLibro buscadorTitulo = new BusquedaPorTitulo();
                BuscadorLibro buscadorISBN = new BusquedaPorISBN();

                //Encadenar los buscadores
                buscadorAutor.setSiguiente(buscadorTitulo);
                buscadorTitulo.setSiguiente(buscadorISBN);

                //Buscar los libros por el criterio y valor
                List<Libro> resultados = buscadorAutor.buscar(criterio,valor);
                llenarTablaConResultados(resultados);
                
                //Se cambia el texto del botón y el estado de busqueda activa
                buscarBtn.setText("Eliminar criterios de búsqueda");
                busquedaActiva = true;
            }
        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioInput;
    private javax.swing.JTextField autorInput;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JComboBox<String> criterioSelect;
    private javax.swing.JTextField generoInput;
    private javax.swing.JTextField isbnInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mensajeErrorLbl;
    private javax.swing.JButton registrarLibroBtn;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JComboBox<String> tipoSelect;
    private javax.swing.JTextField tituloInput;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JTextField valorBusquedaInput;
    // End of variables declaration//GEN-END:variables
}
